version: 0.2

phases:
  pre_build:
    commands:
      - npm install
  build:
    commands:
      - npm run webpack
artifacts:
  files:
    - index.html
    - css/bootstrap.css
    - img/*
    - dist/bundle.js
