version: 0.2

phases:
  build:
    commands:
      - echo nothing to do yet
      - npm install
      - run webpack
artifacts:
  files:
    - index.html
    - css/bootstrap.css
    - img/*
    - dist/bundle.js
