version: 0.2

phases:
  build:
    commands:
      - echo nothing to do yet
artifacts:
  files:
    - index.html
    - css/lightgallery.css
    - css/minilio.css
    - fonts/*
    - img/**/*
    - js/*
    - php/*
    - work/**/*
