version: 0.2

phases:
  build:
    commands:
      - echo nothing to do yet
artifacts:
  files:
    - index.html
    - css/minilio.css
    - work/**/*
    - img/*
    - img/light-gallery/*
    - img/theme-icons/*
