version: 0.2

phases:
  build:
    commands:
      - echo nothing to do yet
artifacts:
  files:
    - index.html
    - css/*
    - fonts/*
    - img/light-gallery/*
    - img/social-icons/*
    - img/theme-icons/*
    - img/*
    - js/*
    - php/*
    - work/**/*
  discard-paths: yes
